# Generated by Django 5.2.6 on 2025-09-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="num_likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
