# Generated by Django 5.2.6 on 2025-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_num_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="num_likes",
        ),
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
